### PR TITLE
Fix dangling file handle on windows.

### LINKED ISSUE #59: Benchmark exporter crashes on Windows
The benchmark exporter crashes when run on a windows machine.

The culprit is an open file handle that prevents a temporary file being moved into the position of the file it should be overwriting.

### PR DESCRIPTION
**Pull request by atmoos**
Fixes the dangling file handle on windows.

Tested both on linux and windows.

closes #59

### CODE REVIEW

**Comment by atmoos** [comment]
Hi @RaduTerec 

This PR fixes a bug in the exporter I wrote to "export" benchmark results. We would/should eventually move this to the BenchView project.

It may prove useful as a _starting point_ for an in-process exporter.

File: source/Quantities.Benchmark/Exporter.cs [hunk 1]
```diff
@@ -11,32 +11,40 @@ public static class Exporter
...
     private static void UpdateSourceFile(FileInfo source, String result)
     {
         var tmpFile = $"{source.FullName}.tmp";
-        using var reader = source.OpenText();
-        using var writer = File.CreateText(tmpFile);
         try {
+            Update(source, tmpFile, result);
+        }
+        finally {
+            File.Move(tmpFile, source.FullName, overwrite: true);
```
Comment (RaduTerec) [inline source/Quantities.Benchmark/Exporter.cs:40]: what if the tmpFile could not be created because of permissions or some other weird reasons?

**Comment by RaduTerec** [comment]
I couldn't reply to your earlier comment, so, for the BenchView I created a [first issue](https://github.com/atmoos/BenchView/issues/1) for exporting the Benchmark results.

What do you think of the names:
- "Glasses" or derivatives (glassy, glassly etc) &ndash; you see the benchmark results better with "glasses"
- "Magnet" &ndash; it's the one place (magnet) for your benchmark results
- "Mosaic" &ndash; you get a mosaic of results, which fit together
- "Puzzle" &ndash; same idea as above.
For the names, you could, of course, put a "Bench" in front of each. I prefer simpler names, because they're catchy 😉
